import Fotter from './foter'
import './globals.css'
import Navbar from "./navbar"

import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hackathon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  
  children,
}: {
 
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className='max-w-[90%] mx-auto'>
          <Navbar/>
        {children}
        <Fotter/>
        </div>
        </body>
      
    </html>
  )
}
